# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT

[package]
name = "tauri-plugin-android-update"
version = "0.2.1"
edition = "2021"
description = "GitHub-releases based updater for Tauri apps on platforms without tauri-plugin-updater support"
license = "MIT-0"
repository = "https://github.com/hrzlgnm/tauri-plugin-android-update"
authors = ["hrzlgnm"]
readme = "README.md"
links = "tauri-plugin-android-update"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = "2"
tauri-plugin-opener = "2.2"
